name: Build with CMake and vcpkg (Windows)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache vcpkg packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/vcpkg/archives
        key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake using Preset
      run: cmake --preset x64-release

    - name: Build using Preset
      run: cmake --build --preset x64-release

    - name: Test
      run: ctest --preset x64-release
